# Generated by Django 3.2 on 2021-05-07 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='dia',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='horarios',
            name='marcado',
            field=models.BooleanField(default=False),
        ),
    ]
