# Generated by Django 3.2 on 2021-05-07 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20210507_0112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horarios',
            new_name='Horario',
        ),
    ]
