# Generated by Django 3.2 on 2021-05-07 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_auto_20210507_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.especialidade'),
        ),
    ]
